services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mybooks_password
      POSTGRES_DB: mybooks_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mybooks_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Servicio para inicializar la aplicación después de que la BD esté lista
  app-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:mybooks_password@db:5432/mybooks_db"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run docker:init

volumes:
  pgdata: